language: java
jdk:
  - openjdk8

services:
  - mongodb

env:
  ORG_GRADLE_PROJECT_sonatypeUsername=xxx
  ORG_GRADLE_PROJECT_sonatypePassword=xxx
  USER_NAME=Travis

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

notifications:
  email:
    - sonunitw12@gmail.com

after_success:
  - ./gradlew coveralls
